name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main   # 👈 build + deploy whenever you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to push to gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
